Added in function total 232  755 drwxr-xr-x  4 doc  4096 Oct 26 15:31 .  755 drwxr-xr-x 34 doc  4096 Oct 23 20:51 ..  644 -rw-r--r--  1 doc  2233 Oct 17 17:28 aliases  644 -rw-r--r--  1 doc 84110 Oct 17 17:28 .docstheme.zsh  644 -rw-r--r--  1 doc  3988 Oct 26 15:31 functions  755 drwxr-xr-x  8 doc  4096 Oct 26 15:32 .git  644 -rw-r--r--  1 doc    53 Oct 17 17:28 .gitignore  755 -rwxr-xr-x  1 doc 15949 Oct 26 03:32 install.sh  644 -rw-r--r--  1 doc  1071 Oct 17 17:28 LICENSE  755 drwxr-xr-x  2 doc  4096 Oct 26 03:32 omz-files  644 -rw-r--r--  1 doc 89629 Oct 17 17:28 .p10k.zsh  644 -rw-r--r--  1 doc  3327 Oct 17 17:28 README.md  644 -rw-r--r--  1 doc  1083 Oct 17 17:28 .zshenv  644 -rw-r--r--  1 doc  3284 Oct 26 03:32 .zshrc to functions file for displaying octal permissions, and added ssh-copy-server-key function for automatically copying ssh keys to servers via ssh.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -98,3 +98,24 @@ update-plugins() {
     fi
   done && cd $HOME
 }
+
+ssh-copy-server-key() {
+  if [ $# -eq 0 ]; then
+    echo "Please specify the server connection details and the public key to install.\n"
+    echo "Ex: $0 $HOME/.ssh/id_rsa.pub user@192.168.1.1\n"
+  elif [ $# -eq 2 ]; then
+    if [[ "$1" == *".pub" ]] && [[ "$2" == *"@"* ]]; then
+      echo "Installing public ssh key $1 to remote server $2 ...\n"
+      ssh-copy-id -i "$1" "$2"
+      ssh -T "$1"
+      [ $? -eq 0 ] && echo "Operation completed successfully.\n" || echo "Error $?: Something went wrong.\n"
+    else
+      echo "Error. Invalid parameters.\n"
+    fi
+  else
+    echo "Please specify the server connection details and the public key to install.\n"
+    echo "Ex: $0 user@192.168.1.1 $HOME/.ssh/id_rsa.pub\n"
+  fi
+}
+
+lso() { ls -alG "$@" | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(" %0o ",k);print}'; }
